# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
title: DIY Embedded system
email: slowstarter80@daum.net
disqus: 
  id:"slowstarter80"
description: > # this means to ignore newlines until "baseurl:"
  Study, make and draw up documents for embedded system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  slowstarter80

# Build settings
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

keywords: 'jekyll,theme,gem-based,blog'
home:
  section1: <h1>Simple Texutre</h1>
  section2: <h2>A gem-based responsive simple texture styled Jekyll theme</h2>
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: # A gem-based responsive simple texture styled Jekyll theme.

timezone: Asia/Seoul

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
